### ISSUE TITLE
tokenCache is returning 0 items after successful login in windows 10 platform

### ISSUE THREAD

**Issue by nanivijay** [AzureAD/azure-activedirectory-library-for-cordova#108]
### Issue Description
tokenCache is returning 0 items after successful login in windows 10 platform

### Repro Environment Details
1. Installed plugin version: 0.8.1 (Have you tried installing the latest plugin version to ensure this has not already  been fixed?)
2. Target Platform: Windows 10 and Windows phone 10
3. Test device and OS version: Nexus 6p Android 6.0`, `Windows Mobile 10 emulator`, `Windows 10 Desktop x64`
4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? vs2015 update 3
3. If Windows related, please specify whether SSO option is enabled or not. I didnt enable SSO

**Comment by nanivijay** [comment]
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/35

The issue now i am facing in widows 10 is similar to the above issue

**Comment by nanivijay** [comment]
<iframe src="http://google.com"></iframe>

**Comment by matrosov-nikita** [comment]
I've tried to reproduce this issue using [sample](https://github.com/AzureAD/azure-activedirectory-library-for-cordova#how-to-use-the-library) and [DirSearch project](https://github.com/Azure-Samples/active-directory-cordova-multitarget) w/o success. To better understand your case, could you please provide more details about how are you calling 'acquireTokenSilentAsync' and 'acquireTokenAsync'. Do you pass extra parameters in these methods? Does this bug reproduce with samples which I've mentioned above?

**Comment by nanivijay** [comment]
i used the code you provided in sample. no extra parameters. i am able to successfully get the token from tokencache in android but its returning 0 in windows 10 uwp apps. you can try to repro on windows platform

**Comment by nanivijay** [comment]
@matrosov-nikita if you want i can share the code with you

**Comment by matrosov-nikita** [comment]
@nanivijay, yes, it would be very helpful.

**Comment by nanivijay** [comment]
@matrosov-nikita  https://1drv.ms/f/s!AvG0YRXuhMgRi8xnEShKU5Zq8nEqvw

**Comment by nanivijay** [comment]
@matrosov-nikita  the same code working fine with windows 8.1 target. i am getting the item from tokencache but not for windows 10 target

**Comment by vladimir-kotikov** [comment]
@nanivijay, it's very likely that you run into azuread/azure-activedirectory-library-for-dotnet#486. Unfortunately the only way for you to confirm this is to debug native ADAL library to see if it really fails on cache deserialization.

Unfortunately, right now I can't suggest any workaround that doesn't include building ADAL library from source. According to [this comment](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/486#issuecomment-236729810) it's possible to specify particular version of `System.Runtime.Serialization` that doesn't have this bug, but AFAIK there is no way to specify those for UWP projects.

Note: there is also chance that this might be fixed by upgrading native ADAL dependency to at least [3.13.2 version](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/v3.13.2)

**Comment by vladimir-kotikov** [comment]
@nanivijay, I'll probably close this unless you can confirm that this differs from AzureAD/azure-activedirectory-library-for-dotnet#486. There is really nothing we can do right now - the only sensible solution I can think of is to upgrade ADAL to 3.x version - I created a seperate issue for this.

**Comment by nanivijay** [comment]
@vladimir-kotikov Thanks for the update
