### ISSUE TITLE
No response from acquireTokenAsync

### ISSUE THREAD

**Issue by lightwaxx** [AzureAD/azure-activedirectory-library-for-cordova#162]
When **acquireTokenAsync** is called, the login is successful but nothing is returned. I recently updated the plugin and reinstalled Android and now it is not working. It working though on an earlier version of the app

1. Installed plugin version:  (Have you tried installing the latest plugin version to ensure this has not already been fixed?) 0.10.1
2. Target Platform: Android
3. Cordova and platform versions: Android 7.0.1 and Android 6.2.3
4. Test device and OS version: Samsung S3
5. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? CLI

**Comment by matrosov-nikita** [comment]
@lightwaxx, thanks for reporting. I'll take a look at this issue, could you please verify whether this bug reproduces with v0.10.0 (just to confirm that it's regression after upgrading SDK library to 1.12.0)

**Comment by matrosov-nikita** [comment]
@lightwaxx, I tried to acquire token using a non-silent method and received it as expected w/ v0.10.1.
It'd be very helpful if you could share your code snippet.
Also, since v0.10 you can set a logger (see https://github.com/AzureAD/azure-activedirectory-library-for-cordova#logging) which collects logs from native SDK library. We can try to analyze them and understand what the problem is.

**Comment by matrosov-nikita** [comment]
@lightwaxx, just a friendly ping

**Comment by lightwaxx** [comment]
Hello @matrosov-nikita . It must have been an issue with an outdated plugin. I removed and reinstalled all plugins and  platforms, reinstalled and it worked perfectly.
