### ISSUE TITLE
Improve documentation in repo home

### ISSUE THREAD

**Issue by sgrebnov** [AzureAD/azure-activedirectory-library-for-cordova#42]
* [x] Main example should be complete, you should be able to copy/paste it and it should work
* [x] Update `Supported platforms` section (+Windows 10)
* [x] Api (methods description/signatures)
* [x] acquireTokenAsync prompt behavior (Always vs Auto which is used by native components)
* [x] Recommendations for signout

**Comment by sgrebnov** [comment]
4. acquireTokenAsync default prompt behavior  (Always vs Auto which is used by native components)

**Comment by SPDoctor** [comment]
Sergei, here is a link to Vittorio's blog where he explains reasoning behind using acquireTokenSilentAsync and then acquireTokenAsync as fail handler - essentially to be able to deal with Windows Phone continuation callback needed because the app is suspended while the auth UI is shown to the user. http://www.cloudidentity.com/blog/2015/04/06/adal-plugin-for-apache-cordova-deep-dive/

**Comment by sgrebnov** [comment]
@SPDoctor thank you for the link!
