### ISSUE TITLE
ADAL not working in Arabic Device Language Android

### ISSUE THREAD

**Issue by mahmoudabogwella** [AzureAD/azure-activedirectory-library-for-cordova#43]
Hello ,
 i cannot login with ADAL when Device Language is Arabic , plugin always delete authentication token and login page open again . kindly note that same code works fine in Android when device language is English.

**Comment by sgrebnov** [comment]
Just tried this on both device and emulator and it worked for me well. @mahmoudabogwella, please describe your test environment and steps in more details:
* cordova version
* android platform version
* ADAL plugin version (we've recently upgraded ADAL native libraries for Android platform so this could be already fixed in the latest cordova version)
* test device model/version
* steps to reproduce

**Comment by mahmoudabogwella** [comment]
@sgrebnov 
cordova android version  : 5.1.0
ADAL plugin version : 0.6.0
Test device Model : nexus 10 
Test Device Android Version : 4.4.2 
Steps to reproduce : auth popup is showed and token is  successfully received  but when i use **acquireTokenSilentAsync**  open auth popup again . and not be able to do any thing else . 

Thanks,

**Comment by sgrebnov** [comment]
Hey @mahmoudabogwella, I was able to reproduce this. The issue appears to be in native ADAL library for android we use, I've reported the following issue: https://github.com/AzureAD/azure-activedirectory-library-for-android/issues/549

**Comment by mahmoudabogwella** [comment]
Thanks for your support :+1:

**Comment by sgrebnov** [comment]
Closing as there is nothing I can do here. I will track this issue in native lib and will update native dependency once this is fixed there.
