### ISSUE TITLE
Failed to login if on a company portal enrolled android device.

### ISSUE THREAD

**Issue by yucaowang** [AzureAD/azure-activedirectory-library-for-cordova#46]
Hi,

I tried the plugin on a company portal enrolled android device, but AAD login failed with error:

V/BasicWebViewClientonPageStarted(25118): 2016-02-25 09:02:09-null-page is started with the url urn:ietf:wg:oauth:2.0:oob?code=AAABAAAAiL...&state=YT1odHRwczovL2xvZ2luLndpbmRvd3MubmV0L2NvbW1vbiZyPWh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0Lw&session_state=a3c44a8f-555c-453e-b9b1-5411bf2618a2 ver:1.1.12
ERROR_WEBVIEW:2016-02-25 09:02:09-null-Webview received an error. Errorcode:-10 net::ERR_UNKNOWN_URL_SCHEME ver:1.1.12 

Seems AAD authentication passed but the redirect url could not recognized? I tried to uninstall company portal then it works fine. Any ideas?

B.t.w. How can I change settings in AuthenticationSettings in cordova?

Thanks

**Comment by sgrebnov** [comment]
Yeah, there is the following setting to manage such behavior, but it is not currently available from cordova
```
AuthenticationSettings.Instance.setSkipBroker(true);
```
I'll take a look
(some related info is available as _Microsoft Intune's Company portal app_ [here](https://github.com/AzureAD/azure-activedirectory-library-for-android)).

**Comment by sgrebnov** [comment]
PS. On windows there is special `adal-use-corporate-network` setting

**Comment by sgrebnov** [comment]
I'm trying to verify this case, but `public boolean canSwitchToBroker()`  ADAL native method always returns false so default local flow is used and works correct. This happens due to [verifyManifestPermissions](https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/662c2a8c49304d09200ed7f2b3fb7c76e3475ae5/src/src/com/microsoft/aad/adal/BrokerProxy.java#L107) test does not pass due to some reason (I can see required permissions in manifest file), investigating...

**Comment by sgrebnov** [comment]
I've fixed permission problem by setting older target sdk version, here are my test results:
1. Company portal auth dialog is showed
2. If I enter my MS credentials then I navigate to company site and authentication flow never finishes.
3. If I enter my test credentials then I cannot pass auth dialog (incorrect user ID or password)

**Comment by sgrebnov** [comment]
@yucaowang  please describe your app settings/experiments in more details. Do you pass authentication through company portal app?

**Comment by yucaowang** [comment]
Hi @sgrebnov , For the redirect URL, I generated a redirect URL for our app using the Powershell script from ADAL Android github, but another issue occurred which caused Company Portal crashing after login on AAD page. Any idea? Please see log snippet below:

V/BasicWebViewClientonPageStarted( 9387): 2016-03-02 05:49:57-null-page is started with the url msauth://com.our.app.package.name/B81MO2ZeSAggS1mDtWtv0a5ADFQ=?code=AAABAAAAiL9Kn2Z27UubvWFPbm0gLd3fgVKbfHhgwmyruHXmijd1sL7k0DOUl0iSUolIsMCBD_n1gFJMOtdUgw5SW4ig7qO5PEyOTDZ1y3hIDz8hO4fA3ArCDAJguitwTqtiuiqgDbh1ZQaEyO6D5oNfa0gd9D_cm0KJk12hqmRkiSSK4E-mK6KxiLoELnovnzRxusPI11IDgw2hivXbUHl0ncZAbOznZXZqqIEUBcvoPIdxM53tgRoqBmo66FZBf0b8AJ9z9Mrl_lP52W4GNMinfOUACJ3Vywii6uizCP-UUkmStY6KaMJL2FQSPlEESNERtTvIxmNsLS0OhI5RSgo9IU0ursodqOy0SFNETJQDkGA67rEbp4I7bfQ4KZQBMT6X5_tabU634F0MSiGt5T22FU8O3i9761OW1UCgdQs2LGmy8RwEMsQfOooto7YGccPT8oPWDbc-cWmOWlR4iLF69LL3HuQj9_3M4V6vpzI_GRo7YRHvL2EDVbLT7FaxBMJyPHD3dhYBOJWy62zddyyf9sRg1tOmycKtET3ANCI4qGFmIWDmjKp12Qu8bk__GfL7t8ncujmOEHfh6LiCSI8o4Oxs1l-YeTH5u25nM9hJr9ZdWmAGwvmnR47VDC-KaT0DfxPTIAA&state=YT1odHRwczovL2xvZ2luLndpbmRvd3MubmV0L2NvbW1vbiZyPWh0dHBzOi8vbWFuYWdlbWVudC5jb3JlLndpbmRvd3MubmV0Lw&session_state=ebdf2673-b58f-4a28-967f-eca59709be7e ver:1.1.12
V/AuthenticationActivity( 9387): 2016-03-02 05:49:57-null-displaySpinner:true showing:true ver:1.1.12
V/BasicWebViewClient( 9387): 2016-03-02 05:49:57-null-Navigation is detected ver:1.1.12
V/BasicWebViewClient( 9387): 2016-03-02 05:49:57-null-It is an install request ver:1.1.12
V/ApplicationReceiver( 9387): 2016-03-02 05:49:57-null-ApplicationReceiver:saveRequest ver:1.1.12
W/System.err( 9387): java.lang.NullPointerException
W/System.err( 9387):     at com.microsoft.aad.adal.BasicWebViewClient.openLinkInBrowser(BasicWebViewClient.java:277)
W/System.err( 9387):     at com.microsoft.aad.adal.BasicWebViewClient.shouldOverrideUrlLoading(BasicWebViewClient.java:263)
W/System.err( 9387):     at com.android.webview.chromium.WebViewContentsClientAdapter.shouldOverrideUrlLoading(WebViewContentsClientAdapter.java:294)
W/System.err( 9387):     at com.android.org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:95)
W/System.err( 9387):     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
W/System.err( 9387):     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:24)
W/System.err( 9387):     at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 9387):     at android.os.Looper.loop(Looper.java:157)
W/System.err( 9387):     at android.app.ActivityThread.main(ActivityThread.java:5867)
W/System.err( 9387):     at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err( 9387):     at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err( 9387):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
W/System.err( 9387):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
W/System.err( 9387):     at dalvik.system.NativeStart.main(Native Method)
F/libc    ( 9387): Fatal signal 6 (SIGABRT) at 0x000024ab (code=-6), thread 9387 (e.companyportal)

**Comment by rwdixon69** [comment]
I am experiencing a similar issue with ADAL 0.6.2 under Company Portal (Intune) for Android devices.  It almost appears that an actual redirect is being attempted to the redirect URI, rather than the return of a Token.  (The configuration works correctly outside of the Company Portal for Android devices and iOS builds are fine both with and without the Company portal....the issue is specific to Android under Company Portal.)

I've tried using the "Microsoft Intune App Wrapping Tool for Android" to set broker parameters, but have had no success there either.  Any ideas?

V/BasicWebViewClientonPageStarted(11073): 2016-03-15 13:41:59-5c8383c6-1d34-435e-9cb5-c044acb70b26-page is started with the url https://login.microsoftonline.com/4a2163b9-03da-429c-979c-d81e9ce06a46/Consent/Grant ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:41:59-5c8383c6-1d34-435e-9cb5-c044acb70b26-displaySpinner:true showing:false ver:1.1.12
V/BasicWebViewClient(11073): 2016-03-15 13:42:00-5c8383c6-1d34-435e-9cb5-c044acb70b26-Navigation is detected ver:1.1.12
V/BasicWebViewClientonPageStarted(11073): 2016-03-15 13:42:00-5c8383c6-1d34-435e-9cb5-c044acb70b26-page is started with the url http://mobile.dar/?code=AAABAAAAiL9Kn2Z27UubvWFPbm0gLeU5fnSvjCd3S-Nu3HYkaD9NsLrfZZXmF51ClX5NlZ9dQHJHJ-g89-lwNY4LzxorAzaLs8mc8VVpRBRnC_m58xFTv0mz6Y5INqO41SYool7IQH0tJZA4gzvvRJiL_6fnWELLLNBv1TTxLf12UZWJ7Ett0KLZMpAx5S4AMdRB-9YpiknbnwLynJspcHK7jIDzC3tF0JQh5T62GlCaLB5kQSwHTocUP9zF2Qh1JQuZXjgGoK5VBriNQUAMcihYL0A31KJfdXuMzOv0QelRHl1qHdlnxOsO2YTEsnCi1UamuFeZEx1TImRuDM4Y-w2Y_e7dQSZgNw2G-WshHZu1xFQFNV7jGSdqA-XqTklYlfT5FSi3Cdb8M6hjJEdVO8JOPtAaq3abSRPOwJvGzzS0bh7CaCYzEmQtpHP9-6X5DDUyFuBmNLyoqQRxsGQWJzPNq0yP7NOae0tu9ZZN2FlTmVkDwX8vFz2AUjZ1EpgdpWl-T68SOKjAWbZMr8Vag7I1EPWdWRdWidqLK49MQk-BD4iWU_Dd1iqqF8ZY1m5kgJeT4vqUFUduuFXwe_3YLkdvQ9RyQQtUAdIQ9phJIGAIYHE7e6ggAA&state=YT1odHRwczovL2xvZ2luLndpbmRvd3MubmV0LzRhMjE2M2I5LTAzZGEtNDI5Yy05NzljLWQ4MWU5Y2UwNmE0NiZyPWh0dHA6Ly93d3cuYmFrZXJjb3JwLmNvbS9GcmFjQmluZGVyTW9iaWxl&session_state=7102fcb3-0b54-4b5b-838f-228830734d3b ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-displaySpinner:true showing:true ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-displaySpinner:false showing:true ver:1.1.12
E/BasicWebViewClient(11073): ERROR_WEBVIEW:2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-Webview received an error. Errorcode:-2 net::ERR_NAME_NOT_RESOLVED ver:1.1.12 
E/AdalLoggerCallback(11073): ADAL: Tag: BasicWebViewClient, Message: 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-Webview received an error. Errorcode:-2 net::ERR_NAME_NOT_RESOLVED ver:1.1.12, MoreInfo: , ErrorCode: ERROR_WEBVIEW
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-Return To Caller:2002 ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-displaySpinner:false showing:false ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-Return To Caller REQUEST_ID:560820234 ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-It is a broker request ver:1.1.12
V/BasicWebViewClient(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-Page finished:http://mobile.dar/?code=AAABAAAAiL9Kn2Z27UubvWFPbm0gLeU5fnSvjCd3S-Nu3HYkaD9NsLrfZZXmF51ClX5NlZ9dQHJHJ-g89-lwNY4LzxorAzaLs8mc8VVpRBRnC_m58xFTv0mz6Y5INqO41SYool7IQH0tJZA4gzvvRJiL_6fnWELLLNBv1TTxLf12UZWJ7Ett0KLZMpAx5S4AMdRB-9YpiknbnwLynJspcHK7jIDzC3tF0JQh5T62GlCaLB5kQSwHTocUP9zF2Qh1JQuZXjgGoK5VBriNQUAMcihYL0A31KJfdXuMzOv0QelRHl1qHdlnxOsO2YTEsnCi1UamuFeZEx1TImRuDM4Y-w2Y_e7dQSZgNw2G-WshHZu1xFQFNV7jGSdqA-XqTklYlfT5FSi3Cdb8M6hjJEdVO8JOPtAaq3abSRPOwJvGzzS0bh7CaCYzEmQtpHP9-6X5DDUyFuBmNLyoqQRxsGQWJzPNq0yP7NOae0tu9ZZN2FlTmVkDwX8vFz2AUjZ1EpgdpWl-T68SOKjAWbZMr8Vag7I1EPWdWRdWidqLK49MQk-BD4iWU_Dd1iqqF8ZY1m5kgJeT4vqUFUduuFXwe_3YLkdvQ9RyQQtUAdIQ9phJIGAIYHE7e6ggAA&state=YT1odHRwczovL2xvZ2luLndpbmRvd3MubmV0LzRhMjE2M2I5LTAzZGEtNDI5Yy05NzljLWQ4MWU5Y2UwNmE0NiZyPWh0dHA6Ly93d3cuYmFrZXJjb3JwLmNvbS9GcmFjQmluZGVyTW9iaWxl&session_state=7102fcb3-0b54-4b5b-838f-228830734d3b ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-AuthenticationActivity onPause unregister receiver ver:1.1.12
V/AuthenticationActivity(11073): 2016-03-15 13:42:01-5c8383c6-1d34-435e-9cb5-c044acb70b26-Spinner at onPause will dismiss ver:1.1.12
D/CordovaInterfaceImpl(15044): Sending activity result to plugin
V/AuthenticationContext(15044): 2016-03-15 13:42:01-4d6144a7-9cbe-4397-849a-800f1d4cc701-Get waiting request: 560820234 ver:1.1.12
V/AuthenticationContext(15044): 2016-03-15 13:42:01-4d6144a7-9cbe-4397-849a-800f1d4cc701-onActivityResult RequestId:560820234 ver:1.1.12
V/AuthenticationContext(15044): 2016-03-15 13:42:01-4d6144a7-9cbe-4397-849a-800f1d4cc701-Error info:Error Code:-2 net::ERR_NAME_NOT_RESOLVED for requestId: 560820234 CorrelationId: 46ce9fdc-2350-4ebd-9661-f38f3ee511ec ver:1.1.12
V/AuthenticationContext(15044): 2016-03-15 13:42:01-4d6144a7-9cbe-4397-849a-800f1d4cc701-Sending error to callback CorrelationId: 46ce9fdc-2350-4ebd-9661-f38f3ee511ec ver:1.1.12

**Comment by sgrebnov** [comment]
Starting working on this..

**Comment by sgrebnov** [comment]
Reproduced

**Comment by rwdixon69** [comment]
@sgrebnov , that is the exact behavior we are observing.  If you change your redirectURI to be a valid URL, accessible from the phone and app, the authentication process will actually present that web page, rather than returning the token, after a successful login.  It's almost as if the "Web Application" path is being taken, rather than the "Native Client Application" logic.  Please let me know if there is any additional information or testing that I can provide to assist.

**Comment by sgrebnov** [comment]
I'm going to quickly create a blank android app and give native library a try to make sure this is Cordova specific (if it will work using standard android app)....will keep you updated...

**Comment by sgrebnov** [comment]
Not sure why, but non of callbacks are fired, investigating this..relocating to home - will be able to continue working on this in a few hrs.. If this is a really blocker and any fix could work then there are two ways to disable broker - you can remove required by blocker permissions from the app or this could be done as separate plugin which just executes single line of code on init: `com.microsoft.aad.adal.AuthenticationSettings.INSTANCE.setSkipBroker(true);`

**Comment by yucaowang** [comment]
@sgrebnov , I agree that the default authentication flow is using broker authenticator if Company Portal is installed, but we'd better expose more APIs of AuthenticationSettings and AuthenticationContext in this cordova plugin.

For this issue:
1. If our app don't need to use broker authenticator, we need AuthenticationSettings.INSTANCE.setSkipBroker(true);
2. If our app need to use broker authenticator, AuthenticationContext.getBrokerRedirectUri() is needed to get the correct "msauth://" redirect URL.

Thanks for your efforts.

**Comment by sgrebnov** [comment]
I've created new ticket to continue discussing special option for broker:
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/53

I don't see any difference on what cordova and standard android app return in case of company app is installed, but Azure AD Application is not configured for broker support (no special redirect uri): `Error info:Error Code:-2 net::ERR_NAME_NOT_RESOLVED for requestId:...` So I believe we should add support to skip broker or even disable it by default  - to be discussed in ticket above.

Currently trying to verify if Cordova correcly support broker app if everything is correctly configured. Crated standard android app and new Azure Application with redirect url returned from `AuthenticationContext.getBrokerRedirectUri()`, but stuck with the following error: `Sorry, but we have trouble with signing you in. .... Additional technical information: The application named msauth://<some string here> was not found in the tenant named <some id>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.` Investigating...

**Comment by sgrebnov** [comment]
I’ve finally correctly set up test application with broker auth support and don’t see anything wrong w/ Cordova app. The only small thing I’ve added to config.xml is the following line which activates broker (w/o this line ADAL does not use broker due to permission check fail when targeting android-23). But this should not be the case as other people see Company Portal login (means broker auth is selected)

<preference name="android-targetSdkVersion" value="22" />

**Comment by rwdixon69** [comment]
@sgrebnov , I implemented the custom plugin, which executes the line of code on init: 
` com.microsoft.aad.adal.AuthenticationSettings.INSTANCE.setSkipBroker(true); `

This did not have any effect on the behavior that we are seeing, in that the callbacks don't appear to be firing, and an actual URL-based redirect still occurs.

**Comment by sgrebnov** [comment]
The latest plugin version in this repo adds special method to enable broker support (has been turned off by default). See https://github.com/AzureAD/azure-activedirectory-library-for-cordova#broker-support for more details.

Please re-open this issue if this does not work you.

**Comment by rwdixon69** [comment]
@sgrebnov , I can confirm that the resolution to #53 does indeed resolve this issue. Thank you very much for your assistance!
