### ISSUE TITLE
Refresh Token is missing on Android 5.0.1

### ISSUE THREAD

**Issue by Dismissile** [AzureAD/azure-activedirectory-library-for-cordova#57]
ADAL for Cordova doesn't seem to be providing a refresh token when a authenticating with my app.

I have two applications set up in my Azure AD:
App 1: set up as Native client application. (
App 2: set up as a Web application.

I am trying to add authentication for App 1  and get a token to call App 2:

var resourceUrl = *APP ID URI for App 2*
var appId = *client id for App 1*
var redirectUrl = *Reply URL for App 1*

authContext.acquireTokenAsync(resourceUrl, appId, redirectUrl)
    .then(function(authResult)) {
        // ...
    });

authResult does not contain a refresh token. How do I get one so I don't have to log in every hour?

**Comment by sgrebnov** [comment]
Hey @Dismissile, pls clarify the following so that I can investigate this

1. ADAL plugin version you are using
2. Target Cordova platform (iOS, Android or Windows)
3. Are you testing on real device or emulator

PS. May be related to
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/54#issuecomment-208380183
https://github.com/AzureAD/azure-activedirectory-library-for-cordova/issues/47

**Comment by Dismissile** [comment]
1. cordova-plugin-ms-adal 0.6.3-dev
2. Android
3. Real Device - Samsung Galaxy S4

**Comment by sgrebnov** [comment]
Pls let me know Android version installed on Samsung device. (Looks like we see related issue on devices with Android OS 4.2 and below)

**Comment by Dismissile** [comment]
It's Android 5.0.1 Lollipop.

**Comment by sgrebnov** [comment]
I've tested plugin on Android L and see that refresh token is returned from server and persisted on device (and then used to update token if I call acquireTokenSilentAsync), but it is NOT exposed to JS as [authenticationResultToJSON](https://github.com/AzureAD/azure-activedirectory-library-for-cordova/blob/master/src/android/SimpleSerialization.java#L52) contains strict list of what should be exposed back (as per spec).

Recommendation here is to call _authContext.acquireTokenSilentAsync_ which should return updated token based on refresh token so you don't need to do any extra work. See example on home page for more details.

@Dismissile, feel free to re-open this issue if you still have any problem.

**Comment by Ahmadre** [comment]
@sgrebnov But what about beeing able to save my session or login forever? For that you have to encrypt the refresh-token, save it to your device and reuse it, it the user openes the App AFTER an hour! For that reason: we definetly need the reftesh token!

Please answer my question asap.

Thank you so much.
Rebar

**Comment by sgrebnov** [comment]
@Ahmadre - that makes sense, but  could you please eloborate why you want to do this manually (including encrypthin) instead of using special method provided by api - `acquireTokenSilentAsync`

**Comment by Ahmadre** [comment]
@sgrebnov Because I can't use that method, when the mobile phone is on airplane or battery is empty, or or or. And no I definetly don't want to use Background processes, because it sucks too much battery life and while said: if the smartphone is offline: there's no chance to refresh and the accessToken will expire. Or can I use the silent method instead of an expired accessToken?
