### ISSUE TITLE
Error: “authentication_ui_failed: The browser based authentication dialog failed to complete. Specified cast is not valid.”

### ISSUE THREAD

**Issue by GauravMahajanMicrosoft** [AzureAD/azure-activedirectory-library-for-cordova#69]
We are not seeing the login popup on a windows 10 device. Logs have the following error: “authentication_ui_failed: The browser based authentication dialog failed to complete. Specified cast is not valid.”

Adal Plugin version: 0.6.2
Target Platform: Windows 10
SSO option: enabled

**Comment by sgrebnov** [comment]
Looks like this is due to missing capabilities in  windows 10 manifest file which has already been fixed in 0.7.0 (https://github.com/AzureAD/azure-activedirectory-library-for-cordova/commit/657c3bcabbf7de8f8d2597d3ee93b5377cdc4a7d). Please update plugin version to the latest and see if you still see the problem.

**Comment by sgrebnov** [comment]
Please re-open if this is still actual.
