### ISSUE TITLE
Android - onActivityResult BROWSER_FLOW data is null

### ISSUE THREAD

**Issue by arijitdas** [AzureAD/azure-activedirectory-library-for-cordova#91]
### Issue Description

In our cordova based app we are repeatedly seeing error (in logcat) saying:
E/AuthenticationContext(2765): `ON_ACTIVITY_RESULT_INTENT_NULL`:2016-08-24 14:29:29-96b7e2c1-1dc9-45b9-96a5-cffc88d86bd9-`onActivityResult BROWSER_FLOW data is null`. ver:1.1.18 

By going through the ADAL plugin code for Android, it looks like that it lost the browser reference. What does it exactly mean and what should be done to fix this? If user cancels out the login process from browser / webView, does it need any special handling?
### Repro Environment Details
1. Installed plugin version:  `0.7.1`
2. Target Platform: `Android` and `iOS`. Currently primarily testing against Android.
3. Test device and OS version: `Nexus 5 Android 6.0 emulator`
4. Are you using Cordova from command line or special Cordova IDE (Visual Studio Cordova Tools, etc), what version? `Visual Studio 2015`, `Cordova CLI 6.3.0`
5. If Windows related, please specify whether SSO option is enabled or not. - NA

**Comment by sgrebnov** [comment]
I've tried to reproduce this issue using the following flows, but don't see this warning. @arijitdas , could you please describe your repro steps. ADAL native lib and cordova plugin are implemented the way so that you don't need to do anything special if user cancels out the login process from browser / webView. I also see there a special [unit test added](https://github.com/AzureAD/azure-activedirectory-library-for-android/commit/43515b97f1b060522ca92b0a3fe762738d3a8783#diff-b22208c3b2db3ae8e26e70b454d9314cR1000) to cover this case (missing intent data), but not sure when it could happen. Ask same question in [adal-for-android](https://github.com/AzureAD/azure-activedirectory-library-for-android) ?

- Call acquireTokenAsync method, then press cancel button in web view.
I see the following parameters passed to [onActivityResult](
https://github.com/AzureAD/azure-activedirectory-library-for-android/blob/d60a0c7c2ef9e2e1d6c78d2e6b7e5e8bbcf706ee/adal/src/main/java/com/microsoft/aad/adal/AcquireTokenRequest.java#L510):
```
requestCode=1001(this is BROWSER_FLOW)
resultCode=2001(this is BROWSER_CODE_CANCEL)
data: Intent instance(not null)
requestId: 143314631
```
Logcat message is
```
V/AuthenticationContext: 2016-09-01 02:34:41-a1b77cf0-e0ad-453a-8adb-8b5f78d83eac-onActivityResult RequestId:143314631 ver:1.1.18
```

- Call acquireTokenAsync method -> press hardwareback button on device
- Call acquireTokenAsync method -> press cancel button in web view which appears during ‘rerouting’ phase (i.e. after login).
- Close the app, switching between apps.

The last two cases don’t call onActivityResult.

**Comment by vladimir-kotikov** [comment]
Closing this as we weren't able to repro this and didn't get any response so far
